app:
  env: development
  port: "8080"
  debug: true
mongo:
  uri: "mongodb://admin:password@localhost:27017"
  db_name: "develop_agent"
redis:
  addr: "localhost:6379"
  password: ""
rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
agent:
  channel_buffer_size: 10
  channel_drain_timeout: 30
auth:
  jwt_private_key_b64: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3dkTXBCbk5tR0tnMWMKTU8rTnBtL3IrTmdkbDRMc3lHTzJGRzEwTzRHc2lwNG1BSjRBdW14dzlrZ0tybGFDSzdxNFJ0UEEveWQ4bCtDKwp1TFB1MnZMM2VSQXowUXJBVDU1LzRpc21pYm5DNnhwaXZaaE0rL21FSUJ3YWtDR1ZXZVVjeHVMSFRGWE1MM01UCmZtSFpieDluaWdTR0pPaWVnMFNXT2YrSTR4K1dLZll4OVQ5UUZwd2JNSHM5aEhYL09EQU9DL3ZoOFFZR2FIZVQKcXdVK0pacDZYUGZ3MCtqNE9OMzI0Mkk2YlQ5RXFYTnBFY0pnemdRMUdOR0F0TXlxM3U2dkxlSkpVNnUzTlVnbQppOUZmTU5Damk0V04xTXJiTW9RTUF0bU1EVHRFeC9aLytCcXBJdG9Nb1hYREFhMktkUFZIWG44eW44M3dVNGM5ClJ3VU91djU3QWdNQkFBRUNnZ0VBVEJIOVE2MzN4TFFLVUcwMFNLK3czbHpINW5IejJscEZTakNpUXhLSVE3YjYKbU0xNVVEME9GT0RIaS9zK2hoMk9BSFZnUW5wOUxtUlhXa0ZNS0xPeFBPaXZDSGVkRit6N0dveUpKN01HSnphdAppRlhOKzVwQkppbWxrL29BMEY4UnU0Y3VLdGNJd2Q3TzBGK1NsV2NuZGI1MVZ0TkFpVjF6eXdPejJ2SjNJb2U1ClNIeUxRcjcxaWd5cGFvc1p3bzE0enU1c0VtdThuVWFHOG1pS0JtMTRUUklOZU1jZ200Q21hK1lZUzRyTmFNa2oKeE9zcXVwUFlJa0duZCtFSFRia285V2xSMm5tTEg0OXByeFFDODBiM2VCTlBtb1ZFclRMSjMreFRaSXpFSUFXNAowaUhwVnpjdVp6bjh4U2dmRlpIOUJwMVY5MnhuRTBFTVBvaitVd1FvNFFLQmdRRDJBNjlTd0RiNVF1bzZRdUw4CnhKeCs0clAvMDBrU1BzSitqVlJzMTFNQnZyTXF6WkUwSGRQTnBpSEg2bHFodWZkUm1TZW9iSFdHZzlJdHJLazYKeEk5cnMvdXRjY1NqZzdBUTlpdHRQUDkzSG42U3paQjNycUZ5Mkd5alZOMlQxMDY4dFVxMnhuL3BlVVpTU1VWbwpOUkhzajJLcHRmOG5SdUVxQTdkZUliZUZxd0tCZ1FDM25sVDN0RkxzN1djZmM1Y1lrY3AySzJvQndnNWxPM3VRCnVXN3JqZnJQelFNSnZUZ3FRQ1cxdzVsODhMdHVXTXJCT3dpMEdpM2NsbGJzejBpZkJhOUF2WUdrUkU0WWVVMmYKelhxSUpmc2ozb2VndVRXazhmdXlPaFRvbmxFY01IeEZpNDFHRlNNL0tybXIvdjhPb3BxWmhFNC9WSk1jQVRncApNMURqVEpENmNRS0JnUUN0dXhKdnhLL052UFI5NmtnenFvQzlsa2o0NjNOWndCcEhsblM5WEI0UlNHTnNZYmtkCjdjWnFIdDBTT2F5Qk16dTFVd3ZQZzdCSEt3WWRIU1p4Q3VnaGJmdllrMVFEQ1Bjb016K2RxQXJjU3h1bGZpZDgKYlVVMFBpUVIvOWR1RlFsVWVFNW4zcXZyNjZtK2FHSHNZalhqTWFyQ0lIVXNmb0I1MUNBRkNKaDZld0tCZ1FDdgp0N0MrWCszZjJJMFFWekRvalZTQVk2bU54eVM1a2dQOUNzZndXaTRFd0wvQWlUai9qZVhJblVmOGZmQVFlSjZICjdyTzBqejBHVlVVWVdJRzUxTm5URGNmTDZLWUgyOFlDUU1TYkdDWFBQTHowZldtdDBQazZwVVN2SEJxbzdHbHcKc0V6aEhZZGVnc2V1cGxkMXJQeGdIM0kyUHZ5TkYwbWtlL3hUbVVsQXNRS0JnR1pXMjEyd2FveThEc0YxRzVhcwpJa1FwVHVBN0VwYkhtcXc0MVNEWTRHbm9HTGowVUxnKzI3V1U1eEF5dWVKUk9IQzU0WEVPZE5pWmlVRklVdWdEClBTSHlScmsxdFd1OXBZa2RPeTlYL3oyd1k5dFBheGFEZHE1dlFLM2YxVW4xci9Za2diay9WejJhbGdOS3ppaWUKVWNHaEdGVlJWaGRJTlFTNVkvamxBaWxGCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
  jwt_issuer: "develop-agent"
  jwt_audience: "develop-agent-users"
  access_ttl_minutes: 15
  refresh_ttl_days: 7
seed:
  force_admin_reset: false
