name: Go Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: src/backend/go.mod

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v2.1.6
        working-directory: src/backend
